package com.besson.arknights.block;

import com.besson.arknights.ArknightsFurniture;
import com.besson.arknights.block.AirtightChemicalSafetyCabin.*;
import com.besson.arknights.block.ChensOffice.*;
import com.besson.arknights.block.ColumbiaCafe.*;
import com.besson.arknights.block.ColumbiaModernHotel.*;
import com.besson.arknights.block.EdgeSolid_OrangeSimpleHome.*;
import com.besson.arknights.block.FreightWarehouse.*;
import com.besson.arknights.block.IllusionaryBiography.*;
import com.besson.arknights.block.LifeCycleModule12.*;
import com.besson.arknights.block.QuickChainPizzaShops.*;
import com.besson.arknights.block.SamiCountryVilla.*;
import com.besson.arknights.block.SecurityBureauLounge.*;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class ModBlocks {
    public static final Block CARDBOARD_BOX = registerBlock("cardboard_box", new CardboardBox(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CARGO_PAD = registerBlock("cargo_pad", new CargoPad(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CARTON_STOOL = registerBlock("carton_stool", new CartonStool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FREIGHT_CARTS = registerBlock("freight_carts", new FreightCarts(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LARGE_SHELVES1 = registerBlock("large_shelves1", new LargeShelves(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LARGE_SHELVES2 = registerBlock("large_shelves2", new LargeShelves(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LARGE_SHELVES3 = registerBlock("large_shelves3", new LargeShelves(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LARGE_SHELVES4 = registerBlock("large_shelves4", new LargeShelves(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MANY_CARDBOARD_BOXES = registerBlock("many_cardboard_boxes", new ManyCardboardBoxes(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PORTABLE_CALCULATOR = registerBlock("portable_calculator", new PortableCalculator(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PRACTICAL_AIR_CUSHION = registerBlock("practical_air_cushion", new PracticalAirCushion(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block QUICK_POSTIT_NOTES = registerBlock("quick_postit_notes", new QuickPostitNotes(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SHIFT_ATTENDANCE_BOARD = registerBlock("shift_attendance_board", new ShiftAttendanceBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block STREET_GRAFFITI = registerBlock("street_graffiti", new StreetGraffiti(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_MINIMALIST_CLOCK = registerBlock("black_minimalist_clock",new BlackMinimalistClock(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_MINIMALIST_DESK_LEFT = registerBlock("black_minimalist_desk_left",new BlackMinimalistDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_MINIMALIST_DESK_RIGHT = registerBlock("black_minimalist_desk_right",new BlackMinimalistDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_ROLLER_BACKREST = registerBlock("black_roller_backrest",new BlackRollerBackrest(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_TABLE_CABINET = registerBlock("black_table_cabinet",new BlackTableCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CLEAR_BLACK_TV = registerBlock("clear_black_tv",new ClearBlackTV(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MINI_BULLETIN_BOARD = registerBlock("mini_bulletin_board",new MiniBulletinBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PORCELAIN_BED = registerBlock("porcelain_bed",new PorcelainBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PORCELAIN_BEDSIDE_TABLE = registerBlock("porcelain_bedside_table",new PorcelainBedsideTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PORCELAIN_WALL_LAMP = registerBlock("porcelain_wall_lamp",new PorcelainWallLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOLID_CHECKERBOARD_BOOKCASE1 = registerBlock("solid_checkerboard_bookcase1",new SolidCheckerboardBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOLID_CHECKERBOARD_BOOKCASE2 = registerBlock("solid_checkerboard_bookcase2",new SolidCheckerboardBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOLID_CHECKERBOARD_BOOKCASE3 = registerBlock("solid_checkerboard_bookcase3",new SolidCheckerboardBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOLID_COLOR_SOFA_DEFAULT = registerBlock("solid_color_sofa_default",new SolidColorSofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOLID_RIGHT_ANGLE_COFFEE_TABLE = registerBlock("solid_right_angle_coffee_table",new SolidRightAngleCoffeeTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CLEAR_ORANGE_TV = registerBlock("clear_orange_tv",new ClearBlackTV(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MINI_BULLETIN_BOARD2 = registerBlock("mini_bulletin_board2",new MiniBulletinBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_BED = registerBlock("orange_bed",new PorcelainBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_BEDSIDE_TABLE = registerBlock("orange_bedside_table",new PorcelainBedsideTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_CHECKERBOARD_BOOKCASE_1 = registerBlock("orange_checkerboard_bookcase1",new SolidCheckerboardBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_CHECKERBOARD_BOOKCASE_2 = registerBlock("orange_checkerboard_bookcase2",new SolidCheckerboardBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_CHECKERBOARD_BOOKCASE_3 = registerBlock("orange_checkerboard_bookcase3",new SolidCheckerboardBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_COLOR_SOFA_DEFAULT = registerBlock("orange_color_sofa_default",new SolidColorSofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_MINIMALIST_CLOCK = registerBlock("orange_minimalist_clock",new BlackMinimalistClock(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_MINIMALIST_DESK_LEFT = registerBlock("orange_minimalist_desk_left",new BlackMinimalistDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_MINIMALIST_DESK_RIGHT = registerBlock("orange_minimalist_desk_right",new BlackMinimalistClock(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_RIGHT_ANGLE_COFFEE_TABLE = registerBlock("orange_right_angle_coffee_table",new SolidRightAngleCoffeeTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_ROLLER_BACKREST = registerBlock("orange_roller_backrest",new BlackRollerBackrest(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_TABLE_CABINET = registerBlock("orange_table_cabinet",new BlackTableCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_WALL_LAMP = registerBlock("orange_wall_lamp",new PorcelainWallLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BASKET_SHAPED_LOW_COFFEE_TABLE = registerBlock("basket_shaped_low_coffee_table",new BasketShapedLowCoffeeTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BROAD_LEAVED_POTTED_PLANTS = registerBlock("broad_leaved_potted_plants",new BroadLeavedPottedPlants(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BROWN_LAZY_SOFA = registerBlock("brown_lazy_sofa",new BrownLazySofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CONIFEROUS_POTTED_PLANT = registerBlock("coniferous_potted_plant",new ConiferousPottedPlant(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ECOLOGICAL_EXHIBITION_CABINET_BASE = registerBlock("ecological_exhibition_cabinet_base",new EcologicalExhibitionCabinetBase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ECOLOGICAL_EXHIBITION_CABINET_MAIN = registerBlock("ecological_exhibition_cabinet_main",new EcologicalExhibitionCabinetMain(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EMBEDDED_SQUARE_CEILING_LIGHT = registerBlock("embedded_square_ceiling_light",new EmbeddedSquareCeilingLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EMBEDDED_WIDE_CEILING_LIGHT = registerBlock("embedded_wide_ceiling_light",new EmbeddedWideCeilingLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EXHIBITION_SPECIMEN_INFORMATION_BOARD = registerBlock("exhibition_specimen_information_board",new ExhibitionSpecimenInformationBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block METAL_BED = registerBlock("metal_bed",new MetalBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SQUARE_BEDSIDE_CABINET = registerBlock("square_bedside_cabinet",new SquareBedsideCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block THICK_LEAVED_POTTED_PLANT = registerBlock("thick_leaved_potted_plant",new ThickLeavedPottedPlant(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CABIN_CEILING_COMPONENTS = registerBlock("cabin_ceiling_components",new CabinCeilingComponents(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CABIN_COMBINATION_DOUBLE_BED = registerBlock("cabin_combination_double_bed",new CabinCombinationDoubleBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CABIN_FIRE_EXTINGUISHER_SET = registerBlock("cabin_fire_extinguisher_set",new CabinFireExtinguisherSet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CABIN_NOTE_BOARD = registerBlock("cabin_note_board",new CabinNoteBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block COMBINATION_ROLLER_BACKREST = registerBlock("combination_roller_backrest",new CombinationRollerBackrest(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block COMBINATION_WORKBENCH_LEFT = registerBlock("combination_workbench_left",new CombinationWorkbench(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block COMBINATION_WORKBENCH_RIGHT = registerBlock("combination_workbench_right",new CombinationWorkbench(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CONTROL_DISPLAY = registerBlock("control_display",new ControlDisplay(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EMBEDDED_DATA_CABINET1 = registerBlock("embedded_data_cabinet1",new EmbeddedDataCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EMBEDDED_DATA_CABINET2 = registerBlock("embedded_data_cabinet2",new EmbeddedDataCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EXPLOSION_PROOF_GARBAGE_BIN = registerBlock("explosion_proof_garbage_bin",new ExplosionProofGarbageBin(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LIFE_CYCLE_MODULE_CONTROL_CONSOLE = registerBlock("life_cycle_module_control_console",new LifeCycleModuleControlConsole(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BAR_COUNTER_CEILING = registerBlock("bar_counter_ceiling",new BarCounterCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_DISPLAY_RACK_COFFEE1 = registerBlock("beverage_display_rack_coffee1",new BeverageDisplayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_DISPLAY_RACK_COFFEE2 = registerBlock("beverage_display_rack_coffee2",new BeverageDisplayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_DISPLAY_RACK_DC = registerBlock("beverage_display_rack_dc",new BeverageDisplayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_DISPLAY_RACK_DRINK = registerBlock("beverage_display_rack_drink",new BeverageDisplayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_DISPLAY_RACK_EMPTY = registerBlock("beverage_display_rack_empty",new BeverageDisplayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_PRICE_LIST = registerBlock("beverage_price_list",new BeveragePriceList(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BOLIVAR_COFFEE_BEANS = registerBlock("bolivar_coffee_beans",new BolivarCoffeeBeans(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BROWN_LEAP_GRID_BOOKCASE1 = registerBlock("brown_leap_grid_bookcase1",new BrownLeapGridBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BROWN_LEAP_GRID_BOOKCASE2 = registerBlock("brown_leap_grid_bookcase2",new BrownLeapGridBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BROWN_LEAP_GRID_BOOKCASE3 = registerBlock("brown_leap_grid_bookcase3",new BrownLeapGridBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block COLUMBIA_STREET_VIEW = registerBlock("columbia_street_view",new ColumbiaStreetView(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CURVED_BOTTOM_HIGH_FOOT_COFFEE_CHAIR = registerBlock("curved_bottom_high_foot_coffee_chair",new CurvedBottomHighFootCoffeeChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LONG_LEAVED_POTTED_PLANT = registerBlock("long_leaved_potted_plant",new LongLeavedPottedPlant(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ONE_LEGGED_COFFEE_TABLE = registerBlock("one_legged_coffee_table",new OneLeggedCoffeeTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PAIRED_COFFEE_CHAIRS = registerBlock("paired_coffee_chairs",new PairedCoffeeChairs(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RED_BRICK_CAFE_BAR_DEFAULT = registerBlock("red_brick_cafe_bar_default",new RedBrickCafeBar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RED_BRICK_STORAGE_CABINET = registerBlock("red_brick_storage_cabinet",new RedBrickStorageCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOFT_CEILING_LIGHT = registerBlock("soft_ceiling_light",new SoftCeilingLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SUSPENDED_CEILING_LIGHT = registerBlock("suspended_ceiling_light",new SuspendedCeilingLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_ONE_LEGGED_TABLE = registerBlock("black_one_legged_table",new BlackOneLeggedTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_RETRO_STOOL = registerBlock("black_retro_stool",new BlackRetroStool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_SIMPLE_LOW_SOFA = registerBlock("black_simple_low_sofa",new BlackSimpleLowSofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_VINTAGE_CHAIR = registerBlock("black_vintage_chair",new BlackVintageChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BRIGHT_HANGING_LAMP = registerBlock("bright_hanging_lamp",new BrightHangingLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DUPLEX_WOODEN_WALL_RAILING = registerBlock("duplex_wooden_wall_railing",new DuplexWoodenWallRailing(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SANDALWOOD_BED = registerBlock("sandalwood_bed",new SandalwoodBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SANDALWOOD_BEDSIDE_CABINET = registerBlock("sandalwood_bedside_cabinet",new SandalwoodBedsideCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SANDALWOOD_LOW_FOOT_CONFERENCE_TABLE = registerBlock("sandalwood_low_foot_conference_table",new SandalwoodLowFootConferenceTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SANDALWOOD_MEETING_BOARD = registerBlock("sandalwood_meeting_board",new SandalwoodMeetingBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DUPLEX_COPPER_WALL_RAILING = registerBlock("duplex_copper_wall_railing",new DuplexWoodenWallRailing(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GRAY_SIMPLE_LOW_SOFA = registerBlock("gray_simple_low_sofa",new BlackSimpleLowSofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block TEAK_BED = registerBlock("teak_bed",new SandalwoodBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block TEAK_BEDSIDE_CABINET = registerBlock("teak_bedside_cabinet",new SandalwoodBedsideCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block TEAK_LOW_FOOT_CONFERENCE_TABLE = registerBlock("teak_low_foot_conference_table",new SandalwoodLowFootConferenceTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WHITE_ONE_LEGGED_TABLE = registerBlock("white_one_legged_table",new BlackOneLeggedTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CUSHION_ROCKING_CHAIR = registerBlock("cushion_rocking_chair",new CushionRockingChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HAND_WOVEN_FIREWOOD_BASKET = registerBlock("hand_woven_firewood_basket",new HandWovenFirewoodBasket(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOG_BACKCHAIR = registerBlock("log_backchair",new LogBackchair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOG_BEAM = registerBlock("log_beam",new LogBeam(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOG_DINING_TABLE = registerBlock("log_dining_table",new LogDiningTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOG_STORAGE_CABINET_DOWN = registerBlock("log_storage_cabinet_down",new LogStorageCabinetDown(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOG_STORAGE_CABINET_UP1 = registerBlock("log_storage_cabinet_up1",new LogStorageCabinetUp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOG_STORAGE_CABINET_UP2 = registerBlock("log_storage_cabinet_up2",new LogStorageCabinetUp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RETRO_CEILING_FAN = registerBlock("retro_ceiling_fan",new RetroCeilingFan(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SPRUCE_VIOLIN = registerBlock("spruce_violin",new SpruceViolin(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block THE_BODY_OF_A_LIVING_CREATURE = registerBlock("the_body_of_a_living_creature",new TheBodyOfaLivingCreature(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block VINTAGE_CHANDELIER = registerBlock("vintage_chandelier",new VintageChandelier(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WOODEN_SOFA_ELEVATED_BED_DOWN = registerBlock("wooden_sofa_elevated_bed_down",new WoodenSofaElevatedBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WOODEN_SOFA_ELEVATED_BED_UP = registerBlock("wooden_sofa_elevated_bed_up",new WoodenSofaElevatedBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ACTIVITY_TABLE = registerBlock("activity_table",new ActivityTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BACKREST_SINGLE_CHAIR = registerBlock("backrest_single_chair",new BackrestSingleChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_CASH_REGISTER = registerBlock("black_cash_register",new BlackCashRegister(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BOWL = registerBlock("pizza_bowl",new PizzaBowl(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DINING_CABINETS = registerBlock("dining_cabinets",new DiningCabinets(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DINING_PLATE = registerBlock("dining_plate",new DiningPlate(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DINING_TRAY_RACK = registerBlock("dining_tray_rack",new DiningTrayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EXIT_INDICATOR_LIGHT = registerBlock("exit_indicator_light",new ExitIndicatorLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FLOOR_STANDING_POSTER_STAND = registerBlock("floor_standing_poster_stand",new FloorStandingPosterStand(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HIGH_STOOL = registerBlock("high_stool",new HighStool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PIZZA_BOX = registerBlock("pizza_box",new PizzaBox(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PIZZA_POSTER = registerBlock("pizza_poster",new PizzaPoster(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PIZZA_PRICE_LIST1 = registerBlock("pizza_price_list1",new PizzaPriceList(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PIZZA_PRICE_LIST2 = registerBlock("pizza_price_list2",new PizzaPriceList(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOFT_LIGHT_CHANDELIERS = registerBlock("soft_light_chandeliers",new SoftLightChandeliers(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_TABLE_HIGH_STOOL = registerBlock("beverage_table_high_stool",new BeverageTableHighStool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BILLBOARD_JUKEBOX = registerBlock("billboard_jukebox",new BillboardJukebox(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_GOLD_FREEZER = registerBlock("black_gold_freezer",new BlackGoldFreezer(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HOTEL_UNIVERSAL_BAR_COUNTER = registerBlock("hotel_universal_bar_counter",new HotelUniversalBarCounter(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_HOTEL_CEILING = registerBlock("modern_hotel_ceiling",new ModernHotelCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_HOTEL_FLOOR_LAMP = registerBlock("modern_hotel_floor_lamp",new ModernHotelFloorLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_HOTEL_PENDANT_LIGHT = registerBlock("modern_hotel_pendant_light",new ModernHotelPendantLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_HOTEL_SOFA_DEFAULT = registerBlock("modern_hotel_sofa_default",new ModernHotelSofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_HOTEL_TEA_TABLE = registerBlock("modern_hotel_tea_table",new ModernHotelTeaTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_HOTEL_WALL_LAMP = registerBlock("modern_hotel_wall_lamp",new ModernHotelWallLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_WALL_HANGING_DECORATION = registerBlock("modern_wall_hanging_decoration",new ModernWallHangingDecoration(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block TOWER_SHAPED_BAR_COUNTER_SUSPENDED_CEILING = registerBlock("tower_shaped_bar_counter_suspended_ceiling",new TowerShapedBarCounterSuspendedCeiling1(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block TOWER_SHAPED_BAR_COUNTER_SUSPENDED_CEILING2 = registerBlock("tower_shaped_bar_counter_suspended_ceiling2",new TowerShapedBarCounterSuspendedCeiling2(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WILLIAM_PIANO_COMBINATION = registerBlock("william_piano_combination",new WilliamPianoCombination(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CABIN_PIPELINE_VALVES = registerBlock("cabin_pipeline_valves",new CabinPipelineValves(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EMERGENCY_PUSH_BED = registerBlock("emergency_push_bed",new EmergencyPushBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MULTIFUNCTIONAL_DISINFECTOR = registerBlock("multifunctional_disinfector",new MultifunctionalDisinfector(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MULTIFUNCTIONAL_ENGINEERING_SHOVEL = registerBlock("multifunctional_engineering_shovel",new MultifunctionalEngineeringShovel(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_AIRWAY = registerBlock("safety_cabin_airway",new SafetyCabinAirway(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_CEILING_LIGHT = registerBlock("safety_cabin_ceiling_light",new SafetyCabinCeilingLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_CONTROL_AIRWAY = registerBlock("safety_cabin_control_airway",new SafetyCabinControlAirway(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_DISINFECTION_LIGHT = registerBlock("safety_cabin_disinfection_light",new SafetyCabinDisinfectionLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_DISINFECTION_ROOM = registerBlock("safety_cabin_disinfection_room",new SafetyCabinDisinfectionRoom(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_ENGINEERING_VEHICLE = registerBlock("safety_cabin_engineering_vehicle",new SafetyCabinEngineeringVehicle(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_FLUORESCENT_LAMP = registerBlock("safety_cabin_fluorescent_lamp",new SafetyCabinFluorescentLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_COMPARTMENT_MATERIAL_BOX = registerBlock("safety_compartment_material_box",new SafetyCompartmentMaterialBox(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SUPPLY_RESOURCE_TANK = registerBlock("supply_resource_tank",new SupplyResourceTank(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CACTUS_POTTED_PLANT = registerBlock("cactus_potted_plant",new CactusPottedPlant(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CHENS_DESK_DEFAULT = registerBlock("chens_desk_default",new ChensDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CHENS_HONORARY_CERTIFICATE = registerBlock("chens_honorary_certificate",new ChensHonoraryCertificate(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CHENS_OFFICE_CHAIR = registerBlock("chens_office_chair",new ChensOfficeChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CHENS_WEAPON_RACK = registerBlock("chens_weapon_rack",new ChensWeaponRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FILE1 = registerBlock("file1",new Files(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FILE2 = registerBlock("file2",new Files(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FLUORESCENT_LAMPS_FOR_THE_GUARD_BUREAU = registerBlock("fluorescent_lamps_for_the_guard_bureau",new FluorescentLampsForTheGuardBureau(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GENERAL_BOOKCASE_OF_THE_GUARD_BUREAU = registerBlock("general_bookcase_of_the_guard_bureau",new GeneralBookcaseOfTheGuardBureau(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GENERAL_GARBAGE_BIN_OF_THE_GUARD_BUREAU = registerBlock("general_garbage_bin_of_the_guard_bureau",new GeneralGarbageBinOfTheGuardBureau(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GUARD_BUREAU_FLUORESCENT_LAMP = registerBlock("guard_bureau_fluorescent_lamp",new GuardBureauFluorescentLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GUARD_BUREAU_HEALTH_ABDOMEN_PLATE = registerBlock("guard_bureau_health_abdomen_plate",new GuardBureauHealthAbdomenPlate(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block OFFICE_CLUE_BOARD = registerBlock("office_clue_board",new OfficeClueBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SPECIAL_UPRIGHT_STAKES_MADE_BY_THE_GUARD_BUREAU = registerBlock("special_upright_stakes_made_by_the_guard_bureau",new SpecialUprightStakesMadeByTheGuardBureau(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SPOTLIGHT_FOR_THE_GUARD_BUREAU = registerBlock("spotlight_for_the_guard_bureau",new SpotlightForTheGuardBureau(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    private static Block registerBlock(String name,Block block){
        registerBlockItem(name,block);
        return Registry.register(Registries.BLOCK,new Identifier(ArknightsFurniture.MOD_ID,name),block);
    }
    private static Item registerBlockItem(String name, Block block){
        return Registry.register(Registries.ITEM,new Identifier(ArknightsFurniture.MOD_ID,name),
                new BlockItem(block,new FabricItemSettings()));
    }
    public static void registerModBlocks(){
        ArknightsFurniture.LOGGER.info("Registering Mod Blocks for" + ArknightsFurniture.MOD_ID);
    }
}
