package com.besson.arknights.block;

import com.besson.arknights.ArknightsFurniture;
import com.besson.arknights.block.AirtightChemicalSafetyCabin.*;
import com.besson.arknights.block.ChensOffice.*;
import com.besson.arknights.block.ColumbiaCafe.*;
import com.besson.arknights.block.ColumbiaModernHotel.*;
import com.besson.arknights.block.EdgeSolid_OrangeSimpleHome.*;
import com.besson.arknights.block.FreightWarehouse.*;
import com.besson.arknights.block.HealthyFastFoodRestaurant.*;
import com.besson.arknights.block.IllusionaryBiography.*;
import com.besson.arknights.block.LancellarBallroom.*;
import com.besson.arknights.block.LifeCycleModule12.*;
import com.besson.arknights.block.LongmenRestaurant.*;
import com.besson.arknights.block.PenguinLogisticsSafeHouse.*;
import com.besson.arknights.block.QuickChainPizzaShops.*;
import com.besson.arknights.block.RhodeIslandModernMusicRehearsalRoom.*;
import com.besson.arknights.block.RhodeIslandWorkshop.*;
import com.besson.arknights.block.SakazMercenaryLounge.*;
import com.besson.arknights.block.SamiCountryVilla.*;
import com.besson.arknights.block.SecurityBureauLounge.*;
import com.besson.arknights.block.SevenCitiesStyleRestaurant.*;
import com.besson.arknights.block.SiestaBeachCottage.*;
import com.besson.arknights.block.SoulSecretSociety.*;
import com.besson.arknights.block.UrsasStudentLounge.*;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class ModBlocks {
    public static final Block CARDBOARD_BOX = registerBlock("cardboard_box", new CardboardBox(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CARGO_PAD = registerBlock("cargo_pad", new CargoPad(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CARTON_STOOL = registerBlock("carton_stool", new CartonStool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FREIGHT_CARTS = registerBlock("freight_carts", new FreightCarts(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LARGE_SHELVES1 = registerBlock("large_shelves1", new LargeShelves(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LARGE_SHELVES2 = registerBlock("large_shelves2", new LargeShelves(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LARGE_SHELVES3 = registerBlock("large_shelves3", new LargeShelves(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LARGE_SHELVES4 = registerBlock("large_shelves4", new LargeShelves(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MANY_CARDBOARD_BOXES = registerBlock("many_cardboard_boxes", new ManyCardboardBoxes(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PORTABLE_CALCULATOR = registerBlock("portable_calculator", new PortableCalculator(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PRACTICAL_AIR_CUSHION = registerBlock("practical_air_cushion", new PracticalAirCushion(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block QUICK_POSTIT_NOTES = registerBlock("quick_postit_notes", new QuickPostitNotes(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SHIFT_ATTENDANCE_BOARD = registerBlock("shift_attendance_board", new ShiftAttendanceBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block STREET_GRAFFITI = registerBlock("street_graffiti", new StreetGraffiti(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block BLACK_MINIMALIST_CLOCK = registerBlock("black_minimalist_clock",new BlackMinimalistClock(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_MINIMALIST_DESK_LEFT = registerBlock("black_minimalist_desk_left",new BlackMinimalistDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_MINIMALIST_DESK_RIGHT = registerBlock("black_minimalist_desk_right",new BlackMinimalistDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_ROLLER_BACKREST = registerBlock("black_roller_backrest",new BlackRollerBackrest(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_TABLE_CABINET = registerBlock("black_table_cabinet",new BlackTableCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CLEAR_BLACK_TV = registerBlock("clear_black_tv",new ClearBlackTV(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MINI_BULLETIN_BOARD = registerBlock("mini_bulletin_board",new MiniBulletinBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PORCELAIN_BED = registerBlock("porcelain_bed",new PorcelainBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PORCELAIN_BEDSIDE_TABLE = registerBlock("porcelain_bedside_table",new PorcelainBedsideTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PORCELAIN_WALL_LAMP = registerBlock("porcelain_wall_lamp",new PorcelainWallLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOLID_CHECKERBOARD_BOOKCASE1 = registerBlock("solid_checkerboard_bookcase1",new SolidCheckerboardBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOLID_CHECKERBOARD_BOOKCASE2 = registerBlock("solid_checkerboard_bookcase2",new SolidCheckerboardBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOLID_CHECKERBOARD_BOOKCASE3 = registerBlock("solid_checkerboard_bookcase3",new SolidCheckerboardBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOLID_COLOR_SOFA_DEFAULT = registerBlock("solid_color_sofa_default",new SolidColorSofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOLID_RIGHT_ANGLE_COFFEE_TABLE = registerBlock("solid_right_angle_coffee_table",new SolidRightAngleCoffeeTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block CLEAR_ORANGE_TV = registerBlock("clear_orange_tv",new ClearBlackTV(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MINI_BULLETIN_BOARD2 = registerBlock("mini_bulletin_board2",new MiniBulletinBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_BED = registerBlock("orange_bed",new PorcelainBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_BEDSIDE_TABLE = registerBlock("orange_bedside_table",new PorcelainBedsideTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_CHECKERBOARD_BOOKCASE_1 = registerBlock("orange_checkerboard_bookcase1",new SolidCheckerboardBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_CHECKERBOARD_BOOKCASE_2 = registerBlock("orange_checkerboard_bookcase2",new SolidCheckerboardBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_CHECKERBOARD_BOOKCASE_3 = registerBlock("orange_checkerboard_bookcase3",new SolidCheckerboardBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_COLOR_SOFA_DEFAULT = registerBlock("orange_color_sofa_default",new SolidColorSofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_MINIMALIST_CLOCK = registerBlock("orange_minimalist_clock",new BlackMinimalistClock(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_MINIMALIST_DESK_LEFT = registerBlock("orange_minimalist_desk_left",new BlackMinimalistDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_MINIMALIST_DESK_RIGHT = registerBlock("orange_minimalist_desk_right",new BlackMinimalistDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_RIGHT_ANGLE_COFFEE_TABLE = registerBlock("orange_right_angle_coffee_table",new SolidRightAngleCoffeeTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_ROLLER_BACKREST = registerBlock("orange_roller_backrest",new BlackRollerBackrest(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_TABLE_CABINET = registerBlock("orange_table_cabinet",new BlackTableCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORANGE_WALL_LAMP = registerBlock("orange_wall_lamp",new PorcelainWallLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block BASKET_SHAPED_LOW_COFFEE_TABLE = registerBlock("basket_shaped_low_coffee_table",new BasketShapedLowCoffeeTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BROAD_LEAVED_POTTED_PLANTS = registerBlock("broad_leaved_potted_plants",new BroadLeavedPottedPlants(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BROWN_LAZY_SOFA = registerBlock("brown_lazy_sofa",new BrownLazySofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CONIFEROUS_POTTED_PLANT = registerBlock("coniferous_potted_plant",new ConiferousPottedPlant(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ECOLOGICAL_EXHIBITION_CABINET_BASE = registerBlock("ecological_exhibition_cabinet_base",new EcologicalExhibitionCabinetBase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ECOLOGICAL_EXHIBITION_CABINET_MAIN = registerBlock("ecological_exhibition_cabinet_main",new EcologicalExhibitionCabinetMain(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EMBEDDED_SQUARE_CEILING_LIGHT = registerBlock("embedded_square_ceiling_light",new EmbeddedSquareCeilingLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EMBEDDED_WIDE_CEILING_LIGHT = registerBlock("embedded_wide_ceiling_light",new EmbeddedWideCeilingLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EXHIBITION_SPECIMEN_INFORMATION_BOARD = registerBlock("exhibition_specimen_information_board",new ExhibitionSpecimenInformationBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block METAL_BED = registerBlock("metal_bed",new MetalBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SQUARE_BEDSIDE_CABINET = registerBlock("square_bedside_cabinet",new SquareBedsideCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block THICK_LEAVED_POTTED_PLANT = registerBlock("thick_leaved_potted_plant",new ThickLeavedPottedPlant(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block CABIN_CEILING_COMPONENTS = registerBlock("cabin_ceiling_components",new CabinCeilingComponents(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CABIN_COMBINATION_DOUBLE_BED = registerBlock("cabin_combination_double_bed",new CabinCombinationDoubleBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CABIN_FIRE_EXTINGUISHER_SET = registerBlock("cabin_fire_extinguisher_set",new CabinFireExtinguisherSet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CABIN_NOTE_BOARD = registerBlock("cabin_note_board",new CabinNoteBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block COMBINATION_ROLLER_BACKREST = registerBlock("combination_roller_backrest",new CombinationRollerBackrest(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block COMBINATION_WORKBENCH_LEFT = registerBlock("combination_workbench_left",new CombinationWorkbench(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block COMBINATION_WORKBENCH_RIGHT = registerBlock("combination_workbench_right",new CombinationWorkbench(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CONTROL_DISPLAY = registerBlock("control_display",new ControlDisplay(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EMBEDDED_DATA_CABINET1 = registerBlock("embedded_data_cabinet1",new EmbeddedDataCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EMBEDDED_DATA_CABINET2 = registerBlock("embedded_data_cabinet2",new EmbeddedDataCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EXPLOSION_PROOF_GARBAGE_BIN = registerBlock("explosion_proof_garbage_bin",new ExplosionProofGarbageBin(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LIFE_CYCLE_MODULE_CONTROL_CONSOLE = registerBlock("life_cycle_module_control_console",new LifeCycleModuleControlConsole(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block BAR_COUNTER_CEILING = registerBlock("bar_counter_ceiling",new BarCounterCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_DISPLAY_RACK_COFFEE1 = registerBlock("beverage_display_rack_coffee1",new BeverageDisplayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_DISPLAY_RACK_COFFEE2 = registerBlock("beverage_display_rack_coffee2",new BeverageDisplayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_DISPLAY_RACK_DC = registerBlock("beverage_display_rack_dc",new BeverageDisplayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_DISPLAY_RACK_DRINK = registerBlock("beverage_display_rack_drink",new BeverageDisplayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_DISPLAY_RACK_EMPTY = registerBlock("beverage_display_rack_empty",new BeverageDisplayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEVERAGE_PRICE_LIST = registerBlock("beverage_price_list",new BeveragePriceList(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BOLIVAR_COFFEE_BEANS = registerBlock("bolivar_coffee_beans",new BolivarCoffeeBeans(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BROWN_LEAP_GRID_BOOKCASE1 = registerBlock("brown_leap_grid_bookcase1",new BrownLeapGridBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BROWN_LEAP_GRID_BOOKCASE2 = registerBlock("brown_leap_grid_bookcase2",new BrownLeapGridBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BROWN_LEAP_GRID_BOOKCASE3 = registerBlock("brown_leap_grid_bookcase3",new BrownLeapGridBookcase(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block COLUMBIA_STREET_VIEW = registerBlock("columbia_street_view",new ColumbiaStreetView(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CURVED_BOTTOM_HIGH_FOOT_COFFEE_CHAIR = registerBlock("curved_bottom_high_foot_coffee_chair",new CurvedBottomHighFootCoffeeChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LONG_LEAVED_POTTED_PLANT = registerBlock("long_leaved_potted_plant",new LongLeavedPottedPlant(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ONE_LEGGED_COFFEE_TABLE = registerBlock("one_legged_coffee_table",new OneLeggedCoffeeTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PAIRED_COFFEE_CHAIRS = registerBlock("paired_coffee_chairs",new PairedCoffeeChairs(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RED_BRICK_CAFE_BAR_DEFAULT = registerBlock("red_brick_cafe_bar_default",new RedBrickCafeBar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RED_BRICK_STORAGE_CABINET = registerBlock("red_brick_storage_cabinet",new RedBrickStorageCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOFT_CEILING_LIGHT = registerBlock("soft_ceiling_light",new SoftCeilingLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SUSPENDED_CEILING_LIGHT = registerBlock("suspended_ceiling_light",new SuspendedCeilingLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block BLACK_ONE_LEGGED_TABLE = registerBlock("black_one_legged_table",new BlackOneLeggedTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_RETRO_STOOL = registerBlock("black_retro_stool",new BlackRetroStool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_SIMPLE_LOW_SOFA = registerBlock("black_simple_low_sofa",new BlackSimpleLowSofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_VINTAGE_CHAIR = registerBlock("black_vintage_chair",new BlackVintageChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BRIGHT_HANGING_LAMP = registerBlock("bright_hanging_lamp",new BrightHangingLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DUPLEX_WOODEN_WALL_RAILING = registerBlock("duplex_wooden_wall_railing",new DuplexWoodenWallRailing(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SANDALWOOD_BED = registerBlock("sandalwood_bed",new SandalwoodBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SANDALWOOD_BEDSIDE_CABINET = registerBlock("sandalwood_bedside_cabinet",new SandalwoodBedsideCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SANDALWOOD_LOW_FOOT_CONFERENCE_TABLE = registerBlock("sandalwood_low_foot_conference_table",new SandalwoodLowFootConferenceTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SANDALWOOD_MEETING_BOARD = registerBlock("sandalwood_meeting_board",new SandalwoodMeetingBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DUPLEX_COPPER_WALL_RAILING = registerBlock("duplex_copper_wall_railing",new DuplexWoodenWallRailing(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GRAY_SIMPLE_LOW_SOFA = registerBlock("gray_simple_low_sofa",new BlackSimpleLowSofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block TEAK_BED = registerBlock("teak_bed",new SandalwoodBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block TEAK_BEDSIDE_CABINET = registerBlock("teak_bedside_cabinet",new SandalwoodBedsideCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block TEAK_LOW_FOOT_CONFERENCE_TABLE = registerBlock("teak_low_foot_conference_table",new SandalwoodLowFootConferenceTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WHITE_ONE_LEGGED_TABLE = registerBlock("white_one_legged_table",new BlackOneLeggedTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block CUSHION_ROCKING_CHAIR = registerBlock("cushion_rocking_chair",new CushionRockingChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HAND_WOVEN_FIREWOOD_BASKET = registerBlock("hand_woven_firewood_basket",new HandWovenFirewoodBasket(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOG_BACKCHAIR = registerBlock("log_backchair",new LogBackchair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOG_BEAM = registerBlock("log_beam",new LogBeam(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOG_DINING_TABLE = registerBlock("log_dining_table",new LogDiningTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOG_STORAGE_CABINET_DOWN = registerBlock("log_storage_cabinet_down",new LogStorageCabinetDown(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOG_STORAGE_CABINET_UP1 = registerBlock("log_storage_cabinet_up1",new LogStorageCabinetUp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOG_STORAGE_CABINET_UP2 = registerBlock("log_storage_cabinet_up2",new LogStorageCabinetUp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RETRO_CEILING_FAN = registerBlock("retro_ceiling_fan",new RetroCeilingFan(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SPRUCE_VIOLIN = registerBlock("spruce_violin",new SpruceViolin(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block THE_BODY_OF_A_LIVING_CREATURE = registerBlock("the_body_of_a_living_creature",new TheBodyOfaLivingCreature(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block VINTAGE_CHANDELIER = registerBlock("vintage_chandelier",new VintageChandelier(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WOODEN_SOFA_ELEVATED_BED_DOWN = registerBlock("wooden_sofa_elevated_bed_down",new WoodenSofaElevatedBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WOODEN_SOFA_ELEVATED_BED_UP = registerBlock("wooden_sofa_elevated_bed_up",new WoodenSofaElevatedBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block ACTIVITY_TABLE = registerBlock("activity_table",new ActivityTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BACKREST_SINGLE_CHAIR = registerBlock("backrest_single_chair",new BackrestSingleChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_CASH_REGISTER = registerBlock("black_cash_register",new BlackCashRegister(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BOWL = registerBlock("pizza_bowl",new PizzaBowl(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DINING_CABINETS = registerBlock("dining_cabinets",new DiningCabinets(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DINING_PLATE = registerBlock("dining_plate",new DiningPlate(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DINING_TRAY_RACK = registerBlock("dining_tray_rack",new DiningTrayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EXIT_INDICATOR_LIGHT = registerBlock("exit_indicator_light",new ExitIndicatorLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FLOOR_STANDING_POSTER_STAND = registerBlock("floor_standing_poster_stand",new FloorStandingPosterStand(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HIGH_STOOL = registerBlock("high_stool",new HighStool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PIZZA_BOX = registerBlock("pizza_box",new PizzaBox(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PIZZA_POSTER = registerBlock("pizza_poster",new PizzaPoster(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PIZZA_PRICE_LIST1 = registerBlock("pizza_price_list1",new PizzaPriceList(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PIZZA_PRICE_LIST2 = registerBlock("pizza_price_list2",new PizzaPriceList(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOFT_LIGHT_CHANDELIERS = registerBlock("soft_light_chandeliers",new SoftLightChandeliers(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block BEVERAGE_TABLE_HIGH_STOOL = registerBlock("beverage_table_high_stool",new BeverageTableHighStool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BILLBOARD_JUKEBOX = registerBlock("billboard_jukebox",new BillboardJukebox(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLACK_GOLD_FREEZER = registerBlock("black_gold_freezer",new BlackGoldFreezer(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HOTEL_UNIVERSAL_BAR_COUNTER = registerBlock("hotel_universal_bar_counter",new HotelUniversalBarCounter(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_HOTEL_CEILING = registerBlock("modern_hotel_ceiling",new ModernHotelCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_HOTEL_FLOOR_LAMP = registerBlock("modern_hotel_floor_lamp",new ModernHotelFloorLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_HOTEL_PENDANT_LIGHT = registerBlock("modern_hotel_pendant_light",new ModernHotelPendantLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_HOTEL_SOFA_DEFAULT = registerBlock("modern_hotel_sofa_default",new ModernHotelSofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_HOTEL_TEA_TABLE = registerBlock("modern_hotel_tea_table",new ModernHotelTeaTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_HOTEL_WALL_LAMP = registerBlock("modern_hotel_wall_lamp",new ModernHotelWallLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MODERN_WALL_HANGING_DECORATION = registerBlock("modern_wall_hanging_decoration",new ModernWallHangingDecoration(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block TOWER_SHAPED_BAR_COUNTER_SUSPENDED_CEILING = registerBlock("tower_shaped_bar_counter_suspended_ceiling",new TowerShapedBarCounterSuspendedCeiling1(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block TOWER_SHAPED_BAR_COUNTER_SUSPENDED_CEILING2 = registerBlock("tower_shaped_bar_counter_suspended_ceiling2",new TowerShapedBarCounterSuspendedCeiling2(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WILLIAM_PIANO_COMBINATION = registerBlock("william_piano_combination",new WilliamPianoCombination(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block CABIN_PIPELINE_VALVES = registerBlock("cabin_pipeline_valves",new CabinPipelineValves(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block EMERGENCY_PUSH_BED = registerBlock("emergency_push_bed",new EmergencyPushBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MULTIFUNCTIONAL_DISINFECTOR = registerBlock("multifunctional_disinfector",new MultifunctionalDisinfector(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MULTIFUNCTIONAL_ENGINEERING_SHOVEL = registerBlock("multifunctional_engineering_shovel",new MultifunctionalEngineeringShovel(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_AIRWAY = registerBlock("safety_cabin_airway",new SafetyCabinAirway(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_CEILING_LIGHT = registerBlock("safety_cabin_ceiling_light",new SafetyCabinCeilingLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_CONTROL_AIRWAY = registerBlock("safety_cabin_control_airway",new SafetyCabinControlAirway(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_DISINFECTION_LIGHT = registerBlock("safety_cabin_disinfection_light",new SafetyCabinDisinfectionLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_DISINFECTION_ROOM = registerBlock("safety_cabin_disinfection_room",new SafetyCabinDisinfectionRoom(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_ENGINEERING_VEHICLE = registerBlock("safety_cabin_engineering_vehicle",new SafetyCabinEngineeringVehicle(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_CABIN_FLUORESCENT_LAMP = registerBlock("safety_cabin_fluorescent_lamp",new SafetyCabinFluorescentLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_COMPARTMENT_MATERIAL_BOX = registerBlock("safety_compartment_material_box",new SafetyCompartmentMaterialBox(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SUPPLY_RESOURCE_TANK = registerBlock("supply_resource_tank",new SupplyResourceTank(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block CACTUS_POTTED_PLANT = registerBlock("cactus_potted_plant",new CactusPottedPlant(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CHENS_DESK_DEFAULT = registerBlock("chens_desk_default",new ChensDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CHENS_HONORARY_CERTIFICATE = registerBlock("chens_honorary_certificate",new ChensHonoraryCertificate(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CHENS_OFFICE_CHAIR = registerBlock("chens_office_chair",new ChensOfficeChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CHENS_WEAPON_RACK = registerBlock("chens_weapon_rack",new ChensWeaponRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FILE1 = registerBlock("file1",new Files(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FILE2 = registerBlock("file2",new Files(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FLUORESCENT_LAMPS_FOR_THE_GUARD_BUREAU = registerBlock("fluorescent_lamps_for_the_guard_bureau",new FluorescentLampsForTheGuardBureau(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GENERAL_BOOKCASE_OF_THE_GUARD_BUREAU = registerBlock("general_bookcase_of_the_guard_bureau",new GeneralBookcaseOfTheGuardBureau(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GENERAL_GARBAGE_BIN_OF_THE_GUARD_BUREAU = registerBlock("general_garbage_bin_of_the_guard_bureau",new GeneralGarbageBinOfTheGuardBureau(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GUARD_BUREAU_FLUORESCENT_LAMP = registerBlock("guard_bureau_fluorescent_lamp",new GuardBureauFluorescentLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GUARD_BUREAU_HEALTH_ABDOMEN_PLATE = registerBlock("guard_bureau_health_abdomen_plate",new GuardBureauHealthAbdomenPlate(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block OFFICE_CLUE_BOARD = registerBlock("office_clue_board",new OfficeClueBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SPECIAL_UPRIGHT_STAKES_MADE_BY_THE_GUARD_BUREAU = registerBlock("special_upright_stakes_made_by_the_guard_bureau",new SpecialUprightStakesMadeByTheGuardBureau(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SPOTLIGHT_FOR_THE_GUARD_BUREAU = registerBlock("spotlight_for_the_guard_bureau",new SpotlightForTheGuardBureau(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block A_SURFERS_BOARD_RACK = registerBlock("a_surfers_board_rack",new ASurfersBoardRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BEACH_COTTAGE_FLOOR_LAMP = registerBlock("beach_cottage_floor_lamp",new BeachCottageFloorLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLUE_AND_WHITE_CANVAS_CURTAINS_LEFT = registerBlock("blue_and_white_canvas_curtains_left",new BlueAndWhiteCanvasCurtains(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLUE_AND_WHITE_CANVAS_CURTAINS_RIGHT = registerBlock("blue_and_white_canvas_curtains_right",new BlueAndWhiteCanvasCurtains(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LAZY_DOUBLE_LOUNGE_CHAIR_DEFAULT = registerBlock("lazy_double_lounge_chair_default",new LazyDoubleLoungeChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LAZY_HIGH_LEGGED_COFFEE_TABLE = registerBlock("lazy_high_legged_coffee_table",new LazyHighLeggedCoffeeTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LAZY_LOUNGE_CHAIR = registerBlock("lazy_lounge_chair",new LazyLoungeChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LAZY_TEA_TABLE = registerBlock("lazy_tea_table",new LazyTeaTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RHODE_ISLAND_SUMMER_CALENDAR = registerBlock("rhode_island_summer_calendar",new RhodeIslandSummerCalendar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SIESTA_CITY_EMBLEM_SOUVENIR = registerBlock("siesta_city_emblem_souvenir",new SiestaCityEmblemSouvenir(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SUMMER_BOAT_CABINET_DOWN = registerBlock("summer_boat_cabinet_down",new SummerBoatCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SUMMER_BOAT_CABINET_UP = registerBlock("summer_boat_cabinet_up",new SummerBoatCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SUMMER_COLLECTION_CABINET = registerBlock("summer_collection_cabinet",new SummerCollectionCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WOODEN_TOP_BEAM = registerBlock("wooden_top_beam",new WoodenTopBeam(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block AMBER = registerBlock("amber",new Guitar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BLAZE = registerBlock("blaze",new Guitar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DARK_CLOUDS = registerBlock("dark_clouds",new Guitar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DRIFTWOOD = registerBlock("driftwood",new Guitar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FROSTING = registerBlock("frosting",new Guitar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GRAPHITE_STEEL = registerBlock("graphite_steel",new Guitar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block REHEARSAL_ROOM_ACCESSORY_HANGING_BOARD = registerBlock("rehearsal_room_accessory_hanging_board",new RehearsalRoomAccessoryHangingBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block REHEARSAL_ROOM_BENCH = registerBlock("rehearsal_room_bench",new RehearsalRoomBench(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block REHEARSAL_ROOM_RECEPTION_DESK = registerBlock("rehearsal_room_reception_desk",new RehearsalRoomReceptionDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block REHEARSAL_ROOM_ROUND_BENCH = registerBlock("rehearsal_room_round_bench",new RehearsalRoomRoundBench(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block REHEARSAL_ROOM_SPOTLIGHT = registerBlock("rehearsal_room_spotlight",new RehearsalRoomSpotLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block REHEARSAL_ROOM_STRAP_HANGING_BOARD = registerBlock("rehearsal_room_strap_hanging_board",new RehearsalRoomStrapHangingBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SHALLOW_SEA = registerBlock("shallow_sea",new Guitar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SPOTLIGHT_CEILING = registerBlock("spotlight_ceiling",new SpotlightCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block STAGE = registerBlock("stage",new Guitar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SUSPENDED_SCROLLING_DISPLAY_SCREEN = registerBlock("suspended_scrolling_display_screen",new SuspendedScrollingDisplayScreen(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block TOUR_EQUIPMENT_COMBINATION = registerBlock("tour_equipment_combination",new TourEquipmentCombination(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WHEAT_FRAGRANCE = registerBlock("wheat_fragrance",new Guitar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WHITE_BIRCH = registerBlock("white_birch",new Guitar(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block YARMA_KHAN_SHELF_DRUM = registerBlock("yarma_khan_shelf_drum",new YarmaKhanShelfDrum(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block AI_STYLE_COLUMN_DOWN = registerBlock("ai_style_column_down",new AiStyleColumn(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block AI_STYLE_COLUMN_MIDDLE = registerBlock("ai_style_column_middle",new AiStyleColumn(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block AI_STYLE_COLUMN_UP = registerBlock("ai_style_column_up",new AiStyleColumn(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BANQUET_HALL_MAIN_SEAT = registerBlock("banquet_hall_main_seat",new BanquetHallMainSeat(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BANQUET_HALL_SECOND_SEAT = registerBlock("banquet_hall_second_seat",new BanquetHallSecondSeat(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BANQUET_TABLE_DEFAULT = registerBlock("banquet_table_default",new BanquetTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block BUST_OF_LANCHENG_GUARD = registerBlock("bust_of_lancheng_guard",new BustOfLanchengGuard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CANDLE_DISPLAY_STOVE = registerBlock("candle_display_stove",new CandleDisplayStove(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CEILING_MOUNTED_CANDLE_CHANDELIER = registerBlock("ceiling_mounted_candle_chandelier",new CeilingMountedCandleChandelier(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DOUBLE_CEILING_CANDLE_CHANDELIER = registerBlock("double_ceiling_candle_chandelier",new DoubleCeilingCandleChandelier(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LANCELLAR_BRAZIER = registerBlock("lancellar_brazier",new LancellarBrazier(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LANCELLAR_LOW_STOOL = registerBlock("lancellar_low_stool",new LancellarLowStool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LANCELLAR_MIRROR = registerBlock("lancellar_mirror",new LancellarMirror(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOCKED_CABINET = registerBlock("locked_cabinet",new LockedCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block ABNORMAL_BEDDING_BED = registerBlock("abnormal_bedding_bed",new AbnormalBeddingBed(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ABNORMAL_BEDDING_LIGHT = registerBlock("abnormal_bedding_light",new AbnormalBeddingLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ABNORMAL_BEDDING_TREE = registerBlock("abnormal_bedding_tree",new AbnormalBeddingTree(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block AUXILIARY_INSTRUMENT_PENDANT_LAMP = registerBlock("auxiliary_instrument_pendant_lamp",new AuxiliaryInstrumentPendantLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CASTING_HONEY_CRUCIBLE = registerBlock("casting_honey_crucible",new CastingHoneyCrucible(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ELEGANT_WOODEN_CHAIRS = registerBlock("elegant_wooden_chairs",new ElegantWoodenChairs(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FRAGMENTED_SEQUENCE_DESK = registerBlock("fragmented_sequence_desk",new FragmentedSequenceDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOCK_THE_NIGHT_STONE_WINDOW = registerBlock("lock_the_night_stone_window",new LockTheNightStoneWindow(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MORE_YIGUA = registerBlock("more_yigua",new MoreYigua(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SEVERAL_YIGUA = registerBlock("several_yigua",new SeveralYigua(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SHAYI_BOOK_GROUP = registerBlock("shayi_book_group",new ShayiBookGroup(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block ADJUSTABLE_ROUND_STOOL = registerBlock("adjustable_round_stool",new AdjustableRoundStool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FLUORESCENT_LAMP_CEILING = registerBlock("fluorescent_lamp_ceiling",new FluorescentLampCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GOODS_TO_BE_CARRIED = registerBlock("goods_to_be_carried",new GoodsToBeCarried(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HIGH_POWER_FLOOR_LAMP = registerBlock("high_power_floor_lamp",new HighPowerFloorLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MULTIFUNCTIONAL_WORKBENCH = registerBlock("multifunctional_workbench",new MultifunctionalWorkbench(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MULTIFUNCTIONAL_WORKBENCH_BOARD = registerBlock("multifunctional_workbench_board",new MultifunctionalWorkbenchBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MULTIFUNCTIONAL_WORKBENCH_COMPUTER = registerBlock("multifunctional_workbench_computer",new MultifunctionalWorkbenchComputer(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block OLD_FASHIONED_RECORD_PLAYER = registerBlock("old_fashioned_record_player",new OldFashionedRecordPlayer(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PENGUIN_CLUE_COLLECTION_BOARD = registerBlock("penguin_clue_collection_board",new PenguinClueCollectionBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RED_GLOVE_COMPARTMENT1 = registerBlock("red_glove_compartment1",new RedGloveCompartment(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RED_GLOVE_COMPARTMENT2 = registerBlock("red_glove_compartment2",new RedGloveCompartment(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RED_GLOVE_COMPARTMENT3 = registerBlock("red_glove_compartment3",new RedGloveCompartment(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAFETY_PARTITION_DOOR = registerBlock("safety_partition_door",new SafetyPartitionDoor(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SOFT_SOFA_DEFAULT = registerBlock("soft_sofa_default",new SoftSofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block TREASURED_BEVERAGE_BUCKET = registerBlock("treasured_beverage_bucket",new TreasuredBeverageBucket(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block CLEANER = registerBlock("cleaner",new Cleaner(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DOUBLE_BEAM_CRANE = registerBlock("double_beam_crane",new DoubleBeamCrane(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FLOODLIGHT_SUSPENDED_CEILING = registerBlock("floodlight_suspended_ceiling",new FloodlightSuspendedCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block INDUSTRIAL_CUTTING_TABLE = registerBlock("industrial_cutting_table",new IndustrialCuttingTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MATERIAL_BOX = registerBlock("material_box",new MaterialBox(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block MECHANICAL_ARM = registerBlock("mechanical_arm",new MechanicalArm(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block STAGING = registerBlock("staging",new Staging(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WEAPON_STORAGE_CABINET = registerBlock("weapon_storage_cabinet",new WeaponStorageCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WHITE_ROUND_STOOL = registerBlock("white_round_stool",new WhiteRoundStool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WORKSHOP_BLACKBOARD = registerBlock("workshop_blackboard",new WorkshopBlackboard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block BAMBOO_SCREEN = registerBlock("bamboo_screen",new BambooScreen(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CEILING_LAMP = registerBlock("ceiling_lamp",new CeilingLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CORNER_WOODEN_DEFAULT = registerBlock("corner_wooden_default",new CornerWooden(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ELECTRIC_FRYING_TABLE = registerBlock("electric_frying_table",new ElectricFryingTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FOCUS_LAMP = registerBlock("focus_lamp",new FocusLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FOOD_WORKSHOP_DINING_TABLE = registerBlock("food_workshop_dining_table",new FoodWorkshopDiningTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FOOD_WORKSHOP_ROUND_STOOL = registerBlock("food_workshop_round_stool",new FoodWorkshopRoundStool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HALF_MASKED_SCREEN = registerBlock("half_masked_screen",new HalfMaskedScreen(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HEXAGONAL_PALACE_LAMP = registerBlock("hexagonal_palace_lamp",new HexagonalPalaceLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block INSCRIPTION_CEILING_DEFAULT = registerBlock("inscription_ceiling_default",new InscriptionCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block INSCRIPTION_CEILING_FANG = registerBlock("inscription_ceiling_fang",new InscriptionCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block INSCRIPTION_CEILING_JIAO = registerBlock("inscription_ceiling_jiao",new InscriptionCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block INSCRIPTION_CEILING_LONG = registerBlock("inscription_ceiling_long",new InscriptionCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block INSCRIPTION_CEILING_MENG = registerBlock("inscription_ceiling_meng",new InscriptionCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block INSCRIPTION_CEILING_MENU1 = registerBlock("inscription_ceiling_menu1",new InscriptionCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block INSCRIPTION_CEILING_MENU2 = registerBlock("inscription_ceiling_menu2",new InscriptionCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block INSCRIPTION_CEILING_ZI = registerBlock("inscription_ceiling_zi",new InscriptionCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORNAMENTAL_PLANT = registerBlock("ornamental_plant",new OrnamentalPlant(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ORNAMENTAL_POTTED_PLANTS = registerBlock("ornamental_potted_plants",new OrnamentalPottedPlants(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SQUARE_BENCH = registerBlock("square_bench",new SquareBench(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block STEWED_POT_PLATFORM = registerBlock("stewed_pot_platform",new StewedPotPlatform(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block STEWED_POT_PLATFORM_POT = registerBlock("stewed_pot_platform_pot",new StewedPotPlatformPot(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block COLD_FRESH_FOOD_CABINET_DEFAULT = registerBlock("cold_fresh_food_cabinet_default",new ColdFreshFoodCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DAILY_RECOMMENDATIONS = registerBlock("daily_recommendations",new DailyRecommendations(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block GREEN_DOUBLE_SOFA_DEFAULT = registerBlock("green_double_sofa_default",new GreenDoubleSofa(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HEALTH_DECORATION_SIGN = registerBlock("health_decoration_sign",new HealthDecorationSign(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HEALTH_DINING_TABLE = registerBlock("health_dining_table",new HealthDiningTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HEALTH_PRICE_LIST = registerBlock("health_price_list",new HealthPriceList(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HEALTH_SERVICE_DESK = registerBlock("health_service_desk",new HealthServiceDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HEALTH_SERVICE_DESK_CASHIER = registerBlock("health_service_desk_cashier",new HealthServiceDeskCashier(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HEALTH_SPOTLIGHT = registerBlock("health_spotlight",new HealthSpotlight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block ICED_JUICE_MAKER = registerBlock("iced_juice_maker",new IcedJuiceMaker(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RELAXED_GARDEN_CEILING = registerBlock("relaxed_garden_ceiling",new RelaxedGardenCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SELF_SERVICE_ORDERING_MACHINE = registerBlock("self_service_ordering_machine",new SelfServiceOrderingMachine(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SELF_SERVICE_VENDING_MACHINE = registerBlock("self_service_vending_machine",new SelfServiceVendingMachine(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block BEER_STORAGE_CABINET = registerBlock("beer_storage_cabinet",new BeerStorageCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CLEAN_SERVICE_DESK_DEFAULT = registerBlock("clean_service_desk_default",new CleanServiceDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DOUBLE_ROW_SOFA_SEAT_DEFAULT = registerBlock("double_row_sofa_seat_default",new DoubleRowSofaSeat(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DOUBLE_ROW_SOFA_SEAT_DESK = registerBlock("double_row_sofa_seat_desk",new DoubleRowSofaSeatDesk(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FOOD_INSULATION_CABINET = registerBlock("food_insulation_cabinet",new FoodInsulationCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HIGH_FOOT_PRICE_LIST = registerBlock("high_foot_price_list",new HighFootPriceList(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LARGE_PROMOTIONAL_BOARD = registerBlock("large_promotional_board",new LargePromotionalBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RESTAURANT_PROMOTIONAL_BOARD = registerBlock("restaurant_promotional_board",new RestaurantPromotionalBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SEVEN_CITY_STYLE_WARM_LIGHT_CHANDELIER = registerBlock("seven_city_style_warm_light_chandelier",new SevenCityStyleWarmLightChandelier(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block BULLETPROOF_GLASS_PARTITION = registerBlock("bulletproof_glass_partition",new BulletproofGlassPartition(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block DETONATOR_MAKING_TOOL = registerBlock("detonator_making_tool",new DetonatorMakingTool(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HANGING_DART_PLATE = registerBlock("hanging_dart_plate",new HangingDartPlate(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HANGING_STORAGE_RACK = registerBlock("hanging_storage_rack",new HangingStorageRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HIGH_FOOT_DINING_TABLE = registerBlock("high_foot_dining_table",new HighFootDiningTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HIGH_YIELD_EXPLOSIVE_RAW_MATERIALS = registerBlock("high_yield_explosive_raw_materials",new HighYieldExplosiveRawMaterials(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOUNGE_LIGHT_SOURCE_CEILING = registerBlock("lounge_light_source_ceiling",new LoungeLightSourceCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOUNGE_LIGHT_TUBE = registerBlock("lounge_light_tube",new LoungeLightTube(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOUNGE_NOTICE_BOARD = registerBlock("lounge_notice_board",new LoungeNoticeBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOUNGE_PENDANT_LIGHT = registerBlock("lounge_pendant_light",new LoungePendantLight(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOUNGE_SMALL_WALL_LAMP = registerBlock("lounge_small_wall_lamp",new LoungeSmallWallLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block RED_FRAMED_FLOOR_MIRROR = registerBlock("red_framed_floor_mirror",new RedFramedFloorMirror(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAKAZ_BILLIARDS_TABLE = registerBlock("sakaz_billiards_table",new SakazBilliardsTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SAKAZ_PENDULUM = registerBlock("sakaz_pendulum",new SakazPendulum(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SPOILS_DISPLAY_RACK = registerBlock("spoils_display_rack",new SpoilsDisplayRack(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));

    public static final Block CIRCULAR_SUSPENDED_CEILING = registerBlock("circular_suspended_ceiling",new CircularSuspendedCeiling(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block CLUB_BULLETIN_BOARD = registerBlock("club_bulletin_board",new ClubBulletinBoard(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block FLOOR_MOUNTED_BOOKSHELF = registerBlock("floor_mounted_bookshelf",new FloorMountedBookshelf(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block HANGING_LAMP = registerBlock("hanging_lamp",new HangingLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOW_FLOOR_LAMP = registerBlock("low_floor_lamp",new LowFloorLamp(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block LOW_STORAGE_CABINET = registerBlock("low_storage_cabinet",new LowStorageCabinet(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block PORTABLE_PICNIC_STOVE = registerBlock("portable_picnic_stove",new PortablePicnicStove(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block SIMPLE_TOILET_CHAIR = registerBlock("simple_toilet_chair",new SimpleToiletChair(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));
    public static final Block WOODEN_LONG_TABLE = registerBlock("wooden_long_table",new WoodenLongTable(FabricBlockSettings.copyOf(Blocks.STONE).nonOpaque()));



    private static Block registerBlock(String name,Block block){
        registerBlockItem(name,block);
        return Registry.register(Registries.BLOCK,new Identifier(ArknightsFurniture.MOD_ID,name),block);
    }
    private static Item registerBlockItem(String name, Block block){
        return Registry.register(Registries.ITEM,new Identifier(ArknightsFurniture.MOD_ID,name),
                new BlockItem(block,new FabricItemSettings()));
    }
    public static void registerModBlocks(){
        ArknightsFurniture.LOGGER.info("Registering Mod Blocks for" + ArknightsFurniture.MOD_ID);
    }
}
